export const timezones = [
    { value: 'Pacific/Midway', label: 'Midway (GMT-11)' },
    { value: 'America/Adak', label: 'Adak (GMT-10)' },
    { value: 'Pacific/Honolulu', label: 'Honolulu (GMT-10)' },
    { value: 'America/Anchorage', label: 'Anchorage (GMT-9)' },
    { value: 'America/Los_Angeles', label: 'Los Angeles (GMT-8)' },
    { value: 'America/Denver', label: 'Denver (GMT-7)' },
    { value: 'America/Chicago', label: 'Chicago (GMT-6)' },
    { value: 'America/New_York', label: 'New York (GMT-5)' },
    { value: 'America/Sao_Paulo', label: 'Brasília (GMT-3)' },
    { value: 'Atlantic/Azores', label: 'Azores (GMT-1)' },
    { value: 'Europe/London', label: 'London (GMT+0)' },
    { value: 'Europe/Berlin', label: 'Berlin (GMT+1)' },
    { value: 'Europe/Athens', label: 'Athens (GMT+2)' },
    { value: 'Europe/Moscow', label: 'Moscow (GMT+3)' },
    { value: 'Asia/Dubai', label: 'Dubai (GMT+4)' },
    { value: 'Asia/Karachi', label: 'Karachi (GMT+5)' },
    { value: 'Asia/Dhaka', label: 'Dhaka (GMT+6)' },
    { value: 'Asia/Bangkok', label: 'Bangkok (GMT+7)' },
    { value: 'Asia/Manila', label: 'Philippines (GMT+8)' },
    { value: 'Asia/Tokyo', label: 'Tokyo (GMT+9)' },
    { value: 'Australia/Sydney', label: 'Sydney (GMT+10)' },
    { value: 'Pacific/Auckland', label: 'Auckland (GMT+12)' },
];
